version: '3.4'

services:
  server-booking:
    image: photobooking-server-booking
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
    networks:
      - app-network

  client-booking:
    image: photobooking-client-booking
    ports: 
      - "7001:80"
    networks:
      - app-network

  proxy:
    image: photobooking-proxy
    depends_on:
      - server-booking
      - client-booking
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80
    networks:
      - app-network

networks:
  app-network:
    name: app-network